import React from "react";

export default function OurStory() {
  return (
    <div className="bg-[#e5e2df] min-h-screen font-serif text-[#1a1a1a]">
      {/* Hero Section */}
      <section className="relative w-full h-[80vh] overflow-hidden">
        <div
          className="absolute inset-0 bg-cover bg-center scale-105"
          style={{
            backgroundImage: "url('assets/Artisian.webp')",
          }}
        ></div>
        <div className="absolute inset-0 bg-[#e5e2df]/60"></div>
      </section>

      {/* About Us Section */}
      <section className="max-w-5xl mx-auto px-6 md:px-10 py-20 leading-relaxed text-[#1a1a1a]/90">
        <h2 className="text-3xl md:text-4xl font-light mb-6">About Us</h2>

        <p className="mb-5">
          Takshila is a company focused on creating decentralized shared P2P
          economic systems, to enable true freedom in digital business
          environments for all its stakeholders. We are re-engineering luxury
          commerce with a Client-to-Manufacturing™ model that links customers,
          independent designers, and master artisans in a single transparent
          loop—eliminating mark-ups, middlemen, and creative gatekeepers.
        </p>

        <p className="mb-5">
          Customers can co-design ultra-personalized pieces in minutes through
          generative AI, visualize them in real time, and receive museum-grade
          craftsmanship at breakthrough prices. Designers gain a zero-risk
          launchpad where their ideas are published, manufactured, and shipped
          worldwide while they earn lifetime royalties and retain creative
          ownership. Artisans finally step into the spotlight, enjoying fair
          pay, steady demand, and global recognition for heritage skills that
          technology now amplifies rather than replaces.
        </p>

        <p>
          Under the hood, Takshila is a high-growth platform fusing generative
          AI, 3-D printing, and real-time provenance to unlock a trillion-dollar
          creator economy. By turning every imagination into a masterpiece and
          every transaction into a shared win, we are transforming luxury into
          an open, borderless network where creativity itself is the primary
          currency.
        </p>
      </section>

      {/* Mission & Vision Overlay Section */}
      <section className="relative w-full min-h-[90vh] flex items-center justify-center overflow-hidden text-[#1a1a1a]">
        {/* Background Image */}
        <div
          className="absolute inset-0 bg-cover bg-center scale-105"
          style={{
            backgroundImage: "url('assets/MissionVision.webp')",
          }}
        ></div>

        {/* Soft Overlay */}
        <div className="absolute inset-0 bg-[#e5e2df]/60"></div>

        {/* Text Content */}
        <div className="relative z-10 max-w-4xl mx-auto px-6 md:px-10 text-center md:text-left space-y-12">
          <div>
            <h3 className="text-3xl md:text-4xl font-semibold mb-3">
              Our Mission
            </h3>
            <div className="w-16 h-[2px] bg-[#1a1a1a]/70 mx-auto md:mx-0 mb-5"></div>
            <p className="text-[#1a1a1a]/85 leading-relaxed text-[15px] md:text-[16px]">
              To democratize luxury by turning every customer into a co-creator,
              every designer into an entrepreneur, and every artisan into a
              celebrated partner—powered by transparent technology and an
              equitable, shared-value model.
            </p>
          </div>

          <div>
            <h3 className="text-3xl md:text-4xl font-semibold mb-3">
              Our Vision
            </h3>
            <div className="w-16 h-[2px] bg-[#1a1a1a]/70 mx-auto md:mx-0 mb-5"></div>
            <p className="text-[#1a1a1a]/85 leading-relaxed text-[15px] md:text-[16px]">
              We foresee a creative economy where imagination flows freely
              across borders, where bespoke jewelry, textiles, furniture and
              more are co-designed online and handcrafted on demand, and where
              the wealth generated by beauty is distributed to those who make
              it. Takshila will be the connective tissue of that economy—an open
              platform that fuses AI, digital fabrication, and artisan
              mastery—ultimately evolving toward a decentralized,
              community-governed marketplace.
            </p>
          </div>
        </div>
      </section>

      {/* How The Platform Works Section */}
      <section className="bg-[#e5e2df] py-24 px-6 md:px-12 lg:px-24 font-serif text-[#1a1a1a]">
        <h1 className="text-4xl md:text-4xl font-light text-center mb-16 tracking-wide">
          How The Platform Works
        </h1>

        <div className="w-full max-w-6xl mx-auto bg-white/60 backdrop-blur-sm shadow-[0_8px_32px_rgba(0,0,0,0.05)] rounded-3xl border border-[#d8d6d3] overflow-hidden">
          {/* Step 1 */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 md:gap-0 px-6 md:px-10 py-12 border-b border-[#d8d6d3]/70">
            <h2 className="text-2xl md:text-3xl font-light text-center md:text-left">
              Create
            </h2>
            <div className="md:col-span-2 text-[#1a1a1a]/85 text-[15px] space-y-2 leading-relaxed">
              <p>
                • Customers or designers describe an idea or upload a sketch.
              </p>
              <p>
                • Our AI Design Studio instantly generates 3-D concepts — users
                fine-tune details, metals, stones, or fabrics.
              </p>
            </div>
          </div>

          {/* Step 2 */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 md:gap-0 px-6 md:px-10 py-12 border-b border-[#d8d6d3]/70">
            <h2 className="text-2xl md:text-3xl font-light text-center md:text-left">
              Visualize
            </h2>
            <div className="md:col-span-2 text-[#1a1a1a]/85 text-[15px] space-y-2 leading-relaxed">
              <p>
                • Real-time 3-D and augmented-reality try-ons eliminate
                guesswork.
              </p>
              <p>• When approved, the file becomes a digital blueprint.</p>
            </div>
          </div>

          {/* Step 3 */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 md:gap-0 px-6 md:px-10 py-12 border-b border-[#d8d6d3]/70">
            <h2 className="text-2xl md:text-3xl font-light text-center md:text-left">
              Craft
            </h2>
            <div className="md:col-span-2 text-[#1a1a1a]/85 text-[15px] space-y-2 leading-relaxed">
              <p>
                • We 3-D-print high-precision wax models, cast in precious
                metal, then hand-finish through our global artisan network.
              </p>
              <p>• Customers receive photo/video updates at every milestone.</p>
            </div>
          </div>

          {/* Step 4 */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 md:gap-0 px-6 md:px-10 py-12">
            <h2 className="text-2xl md:text-3xl font-light text-center md:text-left">
              Deliver & Celebrate
            </h2>
            <div className="md:col-span-2 text-[#1a1a1a]/85 text-[15px] space-y-2 leading-relaxed">
              <p>
                • Finished pieces arrive with digital provenance, artisan
                profile, and certifications.
              </p>
              <p>
                • Designers and artisans receive instant commission payouts;
                customers receive shareable content to tell the piece’s story —
                fueling the viral loop.
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
