import { useEffect } from "react";



export default function TermsConditions() {
    
      return (
            <>
            <section className="bg-[#e5e2df]">
              <div className="max-w-5xl mx-auto px-6 font-serif md:px-10 py-32 leading-relaxed text-[#1a1a1a]/90 terms-content">
                     <h1 className="text-3xl md:text-4xl font-light mb-6"> Terms & Conditions </h1>

                        <p><strong> Last Updated: August, 2025 </strong></p>
                        <p> By accessing or using Takshila’s website and services (collectively, the “Services”), you agree to be bound by these Terms and Conditions (“Terms”). These Terms form a legal agreement between you (“you” or “User”) and Takshila, Inc. (“Takshila,” “we,” “us,” or “our”). Please read them carefully before using our Services.  </p>
                        <h3> 1. Acceptance of Terms and Eligibility </h3>
                        <ul>
                        <li>
                        <strong> Age Requirement:</strong> The Services are intended for users who are at least 18 years old (or the age of legal majority in your jurisdiction) . By using Takshila, you represent that you meet this age requirement. If you are under 18, you may use the Services only with involvement and consent of a parent or guardian. </li>
                        <li>
                        <strong> Compliance with Laws:</strong> You agree to use the Services only for lawful purposes and in compliance with all applicable laws and regulations. Prohibited Conduct: You may not use the site or our products for any illegal or unauthorized purpose, and you may not violate any laws in your jurisdiction through your use of the Services (including, but not limited to, copyright, export, and consumer protection laws). </li>
                        <li>
                        <strong> Geographic Reach:</strong> Takshila is based in the United States and currently primarily serves U.S. customers, but we welcome users globally. Please be aware that by accessing the Services from outside the U.S., you are responsible for ensuring your use complies with local laws. We make no representations that the Services are appropriate or available in other locations. </li>
                        <li>
                        <strong> Changes &amp; Updates:</strong> Takshila may update or modify these Terms at any time. If we make changes, we will post the updated Terms on our website and update the “Last Updated” date . It is your responsibility to review these Terms periodically for changes. Your
                        continued use of the Services after changes are posted constitutes your acceptance of the revised Terms. </li>
                        </ul>
                        <h3> 2. Accounts and Access </h3>
                        <ul>
                        <li>
                        <strong> Account Creation:</strong> At this time, you may browse and use some Takshila features without creating an account. However, certain functionalities (such as saving design projects, uploading designs, or earning commissions as a designer) may require you to register an account. When creating an account, you agree to provide truthful, current, and complete information and to keep it updated. Using false identities or impersonating others is prohibited. </li>
                        <li>
                        <strong> Account Security:</strong> You are responsible for maintaining the confidentiality of your account login credentials and for all activities that occur under your account. Notify us immediately of any unauthorized use of your account. Takshila is not liable for any loss or damage arising from your failure to protect your account information. </li>
                        <li> <strong> No Fees for Basic Use: </strong> Currently, Takshila does not charge any registration or subscription fees for basic access to the platform. However, Takshila reserves the right to introduce account membership fees, premium services, or subscription models in the future as our business evolves. If we do so, we will provide notice of the new fees or services, and use of such features will be optional unless otherwise stated. </li>
                        <li>
                        <strong> Account Termination: </strong> We reserve the right to refuse service, suspend, or terminate your account at any time, for any reason, at our sole discretion . This may include violations of these Terms, suspected fraudulent activity, or other misuse of the Services. In such cases, we may cancel any pending orders and, if you are a designer, we may withhold any unpaid commissions or royalties related to violations of these Terms . You may terminate your own account at any time by contacting us, though termination will not relieve you of obligations
                        incurred prior to termination (such as payment for any orders already placed). </li>
                        </ul>
                        <h3> 3. Third-Party Platforms and Services </h3>
                        <ul>
                        <li>
                        <strong> E-commerce Platform: </strong> Our online store is currently hosted on a third-party ecommerce platform (e.g., Shopify Inc.), which provides us with the online platform to sell our products and Services to you . By using our Services, you also agree to comply with any relevant terms and conditions of such third-party platforms insofar as they apply to you as a user (for example, Shopify’s acceptable use policies).  </li>
                        <li>
                        <strong> Third-Party Payment Processors:</strong> Takshila uses trusted third-party payment gateways (such as Stripe, PayPal, or similar services) to process customer payments for orders. When you make a purchase, you will provide your payment information to these third-party processors, and the processing of payments is governed by their terms and privacy policies, not just ours . Takshila is not responsible for errors or security breaches on the part of the payment processor . We do not store your full credit card information on our servers. By making a purchase, you authorize us and our payment processors to charge your chosen payment method for the total order amount (including any applicable taxes and shipping fees). </li>
                        <li> <strong> Third-Party AI Services:</strong> If you use our AI-powered design feature, please note that it leverages third-party generative AI models (via API). We instruct these AI services not to
                        produce copyrighted or disallowed content, but the service itself is provided by a third party on an “as-is” basis. Takshila makes no warranty as to the availability, accuracy, or output of the AI service and has no liability for any content generated by these third-party AI tools . (See Section 7 on AI-Generated Designs for more details.) </li>
                        <li>
                        <strong> Third-Party Artisans and Suppliers:</strong> Takshila partners with independent thirdparty artisans and manufacturers to produce the jewelry you design or purchase through our platform. While Takshila carefully selects partners and coordinates the manufacturing process, the actual crafting may be performed by third parties. We will use reasonable efforts to ensure quality and timely fulfillment, but certain aspects (like slight variations in handcrafted items or unforeseen delays) may be outside our direct control. Takshila will not be liable for delays or failures caused by our third-party suppliers beyond our responsibility to communicate with you and provide an appropriate remedy (such as an updated delivery estimate, repair, replacement, or refund as applicable under these Terms). </li>
                        <li>
                        <strong> Third-Party Links:</strong> The Services may include links to other websites or resources that are not operated by Takshila. These links are provided for your convenience only. Takshila is not responsible for the content, products, services, or practices of any thirdparty websites . If you access any third-party website or service via our platform, you do so at your own risk, and any transactions or use of such third-party sites are solely between you and that third party. </li>
                        </ul>
                        <h3> 4. Offerings and Order Process </h3>
                        <ul>
                        <li> <strong>Product Descriptions: </strong> Takshila endeavors to provide accurate descriptions, specifications, and images of jewelry products (including materials, dimensions, gemstone
                        details, etc.). However, all product information is provided for general informational purposes and we do not guarantee that descriptions or images are error-free, complete, or current. For example, the color or appearance of products in images may vary slightly due to lighting or display settings. </li>
                        <li> <strong> Design Services: </strong> Our platform offers unique design services, including AIgenerated design suggestions and a Community Design marketplace. These innovative features allow you to create or select custom jewelry designs. We will strive to turn your chosen
                        designs into reality through our manufacturing partners (subject to feasibility and compliance with these Terms). However, any digital renderings or AI-generated images are conceptual and final produced pieces may have minor differences due to manufacturing or material constraints. We do not warrant that any design generated or displayed will exactly match the final product, though we commit to high-quality craftsmanship for the final jewelry. </li>
                        <li>
                        <strong> Placing an Order: </strong> When you place an order for a product (whether a custom design or a standard catalog item) through Takshila, you are making an offer to purchase that product. We reserve the right to accept or decline any order in our discretion. Your order is considered accepted only when we issue an order confirmation (usually via email) and have received full payment of the purchase price . At that point, a binding contract for sale is formed. If we decline an order, any payment received will be refunded. </li>
                        <li>
                        <strong> Right to Refuse or Cancel: </strong> Takshila reserves the right to refuse any order or service to anyone at any time for any reason . This includes, for example, situations where payment cannot be processed or authorized, suspected fraud, shipping restrictions to your location, an error in product pricing or description, or violation of these Terms . We may also limit or cancel quantities purchased per person or per order at our discretion (for instance, if we suspect orders for resale or distribution) . If we make changes to or cancel an order, we will attempt to notify you using the contact information provided with the order . Takshila shall not be liable for refusing an order, beyond refunding any amount you have paid for that order if payment was already processed . </li>
                        <li> <strong> Availability:</strong> All products and services are subject to availability. Certain jewelry pieces or materials may be limited in quantity or available exclusively online. We reserve the right to discontinue any product at any time. Any offer for any product or service is void where prohibited by law . If an item you order is out-of-stock or unavailable, we will inform you as soon as possible and you may choose an alternative or receive a refund. </li>
                        <li> <strong> Pre-Orders and Quotes: </strong> In some cases (especially for bespoke projects), we may provide a quote or accept a pre-order. Such quotes are estimates and not binding until we confirm the order. If market conditions (e.g., metal prices) or other factors change significantly after a quote but before acceptance, we will notify you of any necessary price adjustments before proceeding. </li>
                        </ul>
                        <h3> 5. Pricing and Payment Terms </h3>
                        <ul>
                        <li>
                        <strong> Currency and Taxes:</strong> All prices on the Takshila platform are listed in U.S. Dollars (USD) unless otherwise noted. Prices exclude any applicable sales tax, VAT, duties, or other governmental fees unless stated. Any such taxes or fees will be added at checkout or are the responsibility of the customer (for example, international customs duties for shipments outside the U.S.) </li>
                        <li> <strong> Dynamic Pricing: </strong> Takshila uses a dynamic pricing model. This means the price of a jewelry piece is calculated based on real-time factors such as selected materials (metals, gemstones), design complexity, labor and artisan costs, and current market rates for precious materials. Prices are subject to change without notice prior to order confirmation . We reserve the right to update product prices at any time to reflect changes in material costs, market conditions, or other business factors . Once you have placed an order and it is confirmed by us, the price is locked in for that order. However, if a pricing error or typo is identified (e.g., a significant mistake in the listed price), we reserve the right to cancel the order (with a full refund) or correct the error in consultation with you. </li>
                        <li>
                        <strong> Payment Process:</strong> When you checkout, you must provide a valid payment method (e.g., credit/debit card, PayPal account, or other accepted method). By submitting payment information, you represent that you are authorized to use the payment method and you authorize Takshila (and our payment processors) to charge the full order amount to that method. </li>
                        <li>
                        <strong> Payment Timing: </strong> Typically, we will charge your payment method at the time of order placement (for custom orders, upfront payment is required for us to begin production). If for any reason your payment cannot be processed or is later disputed, we may cancel the order at our discretion. </li>
                        <li>
                        <strong> Third-Party Fees: </strong> You are responsible for any fees that may be charged by your bank or payment provider (e.g., foreign transaction fees). Takshila only receives the net amount of your payment after such processors take their fees. </li>
                        <li>
                        <strong> Security:</strong> Our payment processing is handled via secure, PCI-compliant gateways. Credit card information is encrypted during transmission and not fully stored on our
                        systems . While we take security seriously, we cannot guarantee the security of data transmitted over the internet, and thus you provide payment information at your own risk. </li>
                        <li>
                        <strong> Failed Charges: </strong> If your payment method is declined or if charges are reversed (e.g., a chargeback) after you have received the product, you agree to promptly provide an alternative payment or return the product to Takshila and cover all associated expenses, and costs. We reserve the right to seek reimbursement through other means allowed by law, including using a debt collection service, for any unpaid amounts owed to us </li>
                        <li>
                        <strong> Promotions and Discounts: </strong> Any promotional prices, coupons, or discounts are subject to their specific terms. We reserve the right to cancel or refuse promotions if we suspect misuse or fraud. Promotions may be time-limited and can be changed or withdrawn by us at any time. </li>
                        </ul>
                        <h3> 6. User-Generated Content and Designs </h3>
                        <p> (This section addresses content provided by users, including jewelry designs, images, text, and any other material you submit or generate on Takshila’s platform.) </p>
                        <ul>
                        <li>
                        <strong>User Content Definition: </strong> “User Content” means any content that you submit, upload, post, create, or otherwise provide to Takshila’s Services. This includes, for example, jewelry design specifications, images (including AI-generated design images based on your prompts), design files or sketches you upload, descriptions or titles for designs, comments or reviews, and any other communications you make on the platform . </li>
                        <li>
                        <strong> Your Ownership: </strong> You retain ownership of any intellectual property rights you
                        already hold in your original User Content. For instance, if you upload a jewelry design you created, you remain the owner of that design. Similarly, any original text or images you post remain yours. Takshila does not claim ownership of your original designs or creative works/ </li>
                        <li>
                        <strong> License to Takshila:</strong> In order to operate our Services, we need certain rights to the content you provide. By submitting or creating User Content on Takshila, you grant us a non-exclusive, worldwide, sublicensable, transferable license to use, copy, modify, display, distribute, and create derivative works from your content as needed to provide the Services . This license is royalty-free, except for the commissions and royalties expressly provided in Section 10 if your design is sold. Specifically, this means:
                        <ul>
                            <li> For custom orders (personal use): If you design a piece (whether via AI or upload) and order it for yourself, you grant us the right to use and modify that design to manufacture your jewelry and to display it to you in your account. We will not sell your custom design to other 3rd party outside Takshila without your permission. </li>
                        <li> For community marketplace designs: If you choose to post a design to the Takshila community or marketplace for sale to others, you grant us the right to display that design publicly (with attribution to you as the designer) and to produce (and modify if necessary for manufacturing) the design whenever someone orders it . This includes the right to use images/renders of the design in our online catalog, listings, marketing materials, or social media to promote the design or Takshila’s services. </li>
                            <li> Derivative works and modifications: Takshila may create or use derivatives of your design for technical reasons — for example, generating 3D renderings, creating wax molds or CAD adjustments for manufacturing, or resizing a model for a customer’s request. The license you give us covers these operations. We will not, however, create derivative designs for sale as new products without treating you as the original designer (meaning you’d be entitled to commission as per Section 10 if we somehow created a spin-off of your design concept). </li>
                            <li> Use for service improvement: We reserve a right to internally use user-generated designs and data to improve our Services (such as training AI models to better understand jewelry prompts, testing our systems, or educational purposes) . Any such use is not for sale or external distribution, and it remains within the scope of providing and improving our Services. </li>
                        </ul>
                        </li>
                        <li>
                        <strong> User Content Guidelines: </strong> You are solely responsible for all content you provide and its legality, reliability, and appropriateness . By providing User Content, you represent and
                        warrant that: 
                        <ul>
                            <li> Originality and Rights: The content is your original creation or you have obtained all necessary rights, licenses, or permissions to use it and to grant Takshila the rights described here. It must not be copied or stolen from any third party . You further warrant that uploading or using your content with our Services will not infringe or violate the intellectual property, privacy, or other rights of any third party . </li>
                        <li> No IP-Infringing Designs: You agree not to upload or create any design that is a replica or obvious imitation of someone else’s protected design, copyrighted image, patented invention, or trademarked logo/trade dress without explicit permission. For example, do not try to recreate famous brand jewelry or use characters/artwork you do not own. Takshila expects that you hold the necessary copyrights or have a legal right to use any design you submit . You acknowledge that prompting the AI with references to known designs or uploading such content may produce infringing results, and you take responsibility for any such outcomes.  </li>
                        <li> No Prohibited Content: Your content (including design prompts, uploaded images, and any text) must not be offensive, obscene, pornographic, harassing, defamatory, hateful, or otherwise unlawful. Content that is fraudulent or misleading is also prohibited. Designs involving violent or dangerous items (e.g., weapons) or that promote illegal activity are not allowed. We also ask that you keep content generally appropriate for a broad audience. </li>
                        <li> Malware and Technical Safeguards: You must not upload any files or content that contain viruses, malware, or any harmful code that could damage our systems or other users’ devices . </li>
                            <li> Accuracy of Information: If you provide descriptive information (for example, a title or description for a community-posted design), it should be accurate and not misleading. Any claims about materials, gemstones, or quality must be truthful and substantiated. (Takshila will provide official material specifications for manufacturing, so your description should not contradict our known specs). </li>
                        </ul>
                            </li>
                        <li>
                        <strong> Content Moderation and Removal:</strong> Takshila does not pre-screen every design or piece of content uploaded, but we reserve the right (though not the obligation) to review, monitor, and/or remove any User Content at our sole discretion . We may remove or disable access to any content that we deem (a) in violation of these Terms or our policies (including our Content Policy), (b) infringing on others’ rights, or (c) otherwise objectionable or harmful. We may do so without prior notice. For example, if we receive a credible complaint or notice (such as a DMCA takedown notice) indicating that a user’s uploaded design is a copy of another’s copyrighted work, we will remove it and notify the designer as appropriate. Users who repeatedly violate intellectual property rights or content rules may have their accounts terminated under our repeat infringer policy. </li>
                        <li>
                        <strong> Reporting Infringement:</strong> If you believe that content on Takshila infringes your intellectual property rights, please notify us through our designated copyright agent or support
                        channel with the necessary information (we will provide a formal DMCA Policy on our site with instructions). We will respond promptly to investigate and, if appropriate, remove the allegedly infringing material, consistent with applicable IP laws and safe harbor provisions. </li>
                        <li>
                        <strong> User Content Is Not Confidential: </strong> Please note that any User Content you post publicly (such as community designs or comments) will be visible to others. Do not share personal or sensitive information in public areas. Designs you post for sale will be viewable (but not downloadable in source form) by potential buyers. We cannot guarantee any secrecy or exclusivity for a design posted publicly—while other users cannot legally copy and sell your exact design via our platform, they might conceive similar ideas independently. If you have a truly unique idea you wish to protect, consider pursuing formal IP protections (patents, design patents, copyrights) and be cautious about public disclosure. </li>
                        <li>
                        <strong> Retention and Backup:</strong> We may retain copies of user-generated designs and content (including after removal) as needed for legal obligations, dispute resolution, or backup purposes. However, we are not obligated to retain any User Content for any specific period. Please keep your own backups of any design files or information you upload, as we cannot guarantee against data loss. </li>
                        <li>
                        <strong> Feedback: </strong> If you submit feedback, suggestions, or ideas to Takshila about our Services (for example, suggestions for new features or improvements), you agree that such feedback is provided voluntarily and we may use it freely without any obligation to you. Any improvements or enhancements based on such feedback remain the sole property of Takshila. </li>
                            </ul>
                        <h3> 7. Special Terms for Designers (Community Marketplace) </h3>
                        <ul>
                        <li>
                        <strong> Designer Role: </strong> By uploading or creating a design and marking it available for others to purchase on the Takshila community marketplace, you become a “Designer” in our community. You can earn money when customers buy jewelry based on your design. These earnings can come in two ways: commissions and/or royalties, as defined below. (Takshila may use slightly different terminology on the platform UI, but the concepts remain as described.) </li>
                        <li>
                        <strong> Commission (Platform-Determined): </strong> A commission is a percentage or portion of the sale price of a product that Takshila may pay out to the designer of that product. The commission structure is determined solely by Takshila and may depend on various factors (promotions, production costs, overall margins, etc.). Takshila, in its discretion, will set the commission rate or amount for designer-created products and reserves the right to change the commission rates at any time . For example, Takshila might set a standard commission rate (e.g., 10% of the net sale price) for community designs, but could adjust this over time or for special cases. We will communicate the current commission rates or policies through the platform or directly to designers (e.g., via a dashboard or FAQ). Changes in commission rates
                        will typically apply to future sales (we would not retroactively change commissions on orders already placed). </li>
                        <li>
                        <strong> Royalties (Designer-Set): </strong> In some cases, especially for original designs you upload, Takshila may allow you to set a “royalty” or markup for your design. This is an amount added to the base price of manufacturing the item, which will be paid to you when the item sells. Essentially, Takshila calculates its base cost for producing the piece (including our margin), and you can specify an additional amount that you want to earn per sale. The sum of base cost + your royalty = the price shown to customers (plus any applicable taxes/shipping). When a sale is made, you earn the royalty amount. We may cap or suggest reasonable royalty ranges to keep prices marketable. For example, if the base cost of a ring is $500 and you set a royalty of $50, the customer price might be $550 (plus tax/shipping), and you’d earn $50 on that sale (subject to the transaction fee or commission adjustments below). </li>
                        <li>
                        <strong> Payouts and Fees:</strong> Your earnings (commission or royalties) will accrue in your designer account. Takshila will typically pay out accumulated earnings on a periodic basis (for instance, monthly) or once a certain minimum threshold is reached (e.g., if we have a minimum payout amount to reduce transaction costs). Crucially, payouts for a specific sale will only be made after that sale is fully completed – meaning the product has been delivered to the buyer and the return/cancellation period has passed without incident. If a customer order is canceled or refunded, or a chargeback occurs, the designer will not receive commission/royalty on that transaction (and if any was already credited, it will be debited/back-charged). We align the payout timing to ensure that the sale is final (i.e., outside any return window) so that designers aren’t paid for orders that don’t stick. </li>
                        <li>
                        <strong> Example:</strong> A customer buys your design for $1000 on January 1. Say your commission/royalty on that is $100. The item is delivered January 20. The customer has a 14-day window to report issues/defects. By February 5, the order is confirmed successful with no return. Your $100 might then be scheduled in the February payout cycle (perhaps mid or end of February). If the customer had returned it by January 30, you would not be paid for that sale. </li>
                        <li>
                        <strong> Adjustments and Transaction Fees: </strong> Takshila may deduct certain small fees or costs from designer payouts. For instance, if our payment provider charges a fee per payout transaction, we might subtract that from your payout, or if there’s a platform service fee or commission fee. If such fees apply, they will be disclosed (e.g., “a 3.5% transaction fee on earned commissions” similar to other platforms) .We aim to be transparent about any such fees in our designer documentation </li>
                        <li>
                        <strong> Design Approval and Removal: </strong> Not every uploaded design may be automatically approved for the marketplace. We reserve the right to review and approve designs before they’re offered for sale to ensure they meet our quality and policy standards. Additionally, Takshila can remove a design from the marketplace at any time if we suspect it violates these Terms, infringes someone’s rights, is not selling enough to justify keeping, or for any other reasonable reason. We might also remove designs at the request of the designer or if the designer’s account is closed. </li>
                        <li>
                        <strong> Changes to Marketplace Service:</strong> We reserve the right to change the way the designer marketplace works, including discontinuing it or changing payout structures, with notice. For instance, we may decide to shift from a commission model to a flat fee model or vice versa. Designers will be informed of any major changes, and continued use of the marketplace after such changes constitutes agreement. </li>
                        <li>
                        <strong> No Employment or Partnership: </strong> As a community designer earning commissions or royalties, you are not an employee, agent, or partner of Takshila. You are an independent creator using the platform. Takshila does not guarantee any minimum earnings or success of your designs. You are free to remove your designs from the marketplace if you choose (as long as no pending orders are outstanding). Note that if you remove a design, any pending orders already placed for that design will still be fulfilled by us, and you’ll still receive applicable earnings for those . However, after removal, the design will no longer be available for new orders. </li>
                        <li>
                        <strong> Commission Adjustments and Chargebacks: </strong> If a designer is found to be in breach of these Terms (for example, uploaded a stolen design or engaged in fraudulent activity), Takshila may withhold or cancel any pending payouts to that designer, including commissions/royalties from legitimate sales, as an offset for damages or as a penalty for the breach . Additionally, if Takshila had to refund a customer or incur costs due to a designer’s breach (such as legal fees for an IP infringement claim), the designer may be held financially responsible. See Section 15 (Indemnification) regarding the designer’s obligation to indemnify Takshila in such cases. </li>
                        <li>
                        <strong> Designer’s Set Royalties:</strong> If our model allows you to set a royalty, we might occasionally need to adjust or cap the amount to keep the final price within reasonable limits or due to technical reasons. We will communicate with you if a change to your set royalty is needed for any product (e.g., if you set an excessively high royalty by mistake or if we change our fee structure such that we need to adjust pricing formulas). Our goal is to maintain a fair balance where designers get rewarded, customers get fair prices, and Takshila covers costs. </li>
                        <li>
                        <strong> Marketing and Promotion: </strong> By participating in the marketplace, you agree that Takshila can promote your designs. This might include featuring them on our homepage, in emails, social media, or advertisements. We will attribute credit to you (typically using your display name or designer name on our platform) when showcasing your design. If you have a personal or brand logo, let us know and we might use it in promotions of your works. However, we might lightly edit listing info for clarity or SEO as needed (we won’t alter the design itself, just maybe the title/description/tags for the site). </li>
                        <li>
                        <strong> Community Conduct:</strong> Interactions in the design community (like forums, comments, messages with customers) should remain professional and courteous. Designers should not disparage customers or Takshila publicly. Any direct dealings with a customer outside the platform regarding a Takshila order are not allowed (e.g., do not try to bypass Takshila and sell directly, as that violates trust and the terms of using the platform). </li>
                        <li>
                        <strong> Future Automation: </strong> Presently, Takshila handles designer payouts and order coordination manually or via basic tools. In the future, we plan to automate more of this process possibly with integrated third-party payout systems or an in-house system. By continuing as a designer, you agree that the method of payout may change (e.g., we might require you to provide a PayPal account, bank account, or sign up for a specific payment service to receive funds). We will notify you of any such requirements in advance. </li>
                        </ul>
                        <h3>7.1 Payout Information, Compliance, and Withholding Rights </h3>
                        <p> In order to process royalty and/or commission payments to you under these Terms, Takshila may require you to provide additional information and documentation, which may include but is not limited to:</p>
                        <ul>
                        <li> <strong>Banking or payment details </strong> necessary to transfer funds (e.g., bank account information, PayPal account, or other approved payment method). </li>
                        <li>
                        <strong> Tax identification information</strong> and forms required under applicable laws (such as W-9 or W-8BEN for U.S. tax compliance) to enable Takshila to report earnings or withhold taxes where legally required. </li>
                        <li>
                        <strong> Know Your Customer (KYC) documentation </strong> or identity verification as may be mandated by applicable regulations, financial partners, or in individual cases to prevent fraud or comply with anti-money laundering (AML) obligations. 
                        <ul>
                        <li> Any other information or documentation reasonably requested by Takshila to ensure legal and regulatory compliance, prevent fraud, or verify your entitlement to payment. </li>
                        <li> You agree to provide such information promptly upon request and to keep it accurate and up-todate. Takshila will handle your personal data in accordance with our Privacy Policy, but you
                        acknowledge and agree that: </li>
                        </ul> </li>
                        <li>
                        <strong> Withholding or Reporting Obligations:</strong> Takshila may be legally required to withhold a portion of your payout for taxes or remit information to government agencies, tax authorities, or other regulatory bodies without further notice to you </li>
                        <li>
                        <strong> Failure to Provide Information:</strong> If you fail to provide required information or documentation, or if the information provided is inaccurate or incomplete, Takshila may, in its sole discretion, withhold or delay payment, cancel future payouts, suspend or terminate your account, and/or report such non-compliance to the relevant authorities </li>
                        <li>
                        <strong>No Liability for Delays Due to Compliance:</strong> Takshila is not responsible for any delays or failure to pay royalties or commissions caused by your failure to meet these requirements or by compliance checks, banking delays, or regulatory reviews beyond our reasonable control. </li>
                        <li>
                        <strong> Payment Method Restrictions:</strong> Takshila reserves the right to limit payment methods available based on your location, applicable laws, or operational considerations, and to require you to use specific third-party payment processors or systems to receive funds. </li>
                        <li>
                        <strong> Costs of Transfer: </strong> Unless prohibited by law, any transfer fees, currency conversion charges, or other bank-imposed fees are your responsibility and may be deducted from your payout. </li>
                        </ul>
                        <h3>8. Intellectual Property Rights </h3>
                        <ul>
                        <li>
                        <strong> Takshila’s Intellectual Property:</strong> All content and materials available on the Takshila website or provided through the Services that are not User Content (as defined above) are the property of Takshila or our licensors. This includes (but is not limited to) the Takshila name and logo, website design and layout, text, graphics, images (other than user-generated design images), software, and the compilation of content on the site. These are protected by copyright, trademark, and other intellectual property laws. You may not copy, distribute, modify, or create derivative works from our proprietary content without our prior written consent, except as allowed by law (such as fair use) . You are permitted to use the site and its content only for personal, non-commercial purposes (for example, to view products, to design and order jewelry for yourself, or to decide on purchases). Any other use of our content, including scraping, data mining, or use of our images for your own sales, is strictly prohibited </li>
                        <li>
                        <strong> Use of Takshila Marks:</strong> The Takshila name, logo, and any slogans or taglines are trademarks of Takshila. You may not use these marks in any manner likely to confuse customers or imply endorsement or affiliation without explicit permission. For example, you
                        cannot use “Takshila” in the name of your own business or website related to jewelry without our consent. </li>
                        <li>
                        <strong> Third-Party IP on the Site:</strong> Takshila may display some content that is owned by third parties (e.g., artisan or designer brand logos, third-party software, or stock images). All such content remains the property of its respective owners and is used by Takshila under license or permission. You must respect those rights as well. </li>
                        <li>
                        <strong> No License by Implication:</strong> Except for the limited, revocable license to use the Services under these Terms, nothing on the site shall be construed as granting any license or rights to any intellectual property of Takshila or any third party, whether by estoppel, implication, or otherwise. </li>
                        <li>
                        <strong> Feedback IP: </strong> As stated earlier, any feedback or suggestions you provide regarding our Services can be used by us without restriction, and no rights in any improvements based on such feedback are granted to you. We might patent or otherwise protect features or methods introduced to the platform, and you agree not to claim any rights in those based on your feedback contributions. </li>
                        </ul>
                        <h3> 9. Privacy and Data Protection </h3>
                        <ul>
                        <li>
                        <strong> Privacy Policy:</strong> Your submission of personal information to Takshila (such as when creating an account, placing an order, or using the AI design feature) is governed by our Privacy Policy . Our Privacy Policy details how we collect, use, share, and protect your personal data. By using the Services, you consent to the collection and use of information as outlined in that policy. If you do not agree with our data practices, please do not use the Services </li>
                        <li>
                        <strong> GDPR and International Users:</strong> If you are located in the European Economic Area (EEA), United Kingdom, or other regions with data protection laws (like the GDPR), Takshila is committed to complying with those laws. This may include providing you with certain rights (such as access, correction, deletion, or portability of your personal data) as described in our Privacy Policy. We will only process your personal data when we have a lawful basis to do so, such as your consent (for example, if you opt in to marketing), to perform our contract with you (fulfilling orders), or to comply with legal obligations. </li>
                        <li>
                        <strong> CCPA (California Residents):</strong> If you are a California resident, you have specific rights under the California Consumer Privacy Act (CCPA) regarding your personal information. Our Privacy Policy explains how California residents can exercise those rights (like requesting information on data collected or asking us not to sell personal info). Note that Takshila does not “sell” personal information in the traditional sense; we use personal data primarily to fulfill orders and provide Services. </li>
                        <li>
                        <strong> Data Security:</strong> We implement reasonable security measures to protect your personal data. However, no website or Internet transmission is completely secure. You understand that any data you provide is at your own risk and subject to the possibility of unauthorized access (though we certainly strive to prevent that). If we become aware of a data breach affecting your personal information, we will notify you as required by applicable laws. </li>
                        <li>
                        <strong> Data Retention:</strong> We retain personal data as long as necessary to fulfill the purposes it was collected for, including to comply with legal, accounting, or reporting requirements. For example, we may retain transaction records to comply with tax laws, or account information until you delete your account (and thereafter if needed for legal claims). </li>
                        <li>
                        <strong> AI Design Data:</strong> Designs generated via the AI feature and any user prompts may be stored by Takshila (and possibly by the third-party AI service in accordance with their policies). We attribute stored designs to your user account for your reference and re-use. By using the AI feature, you acknowledge that the prompt and generated image may be processed by a third-party AI provider, and you consent to such processing. We will not use your specific AI-generated design for another customer’s order unless you choose to share/post it in the community marketplace </li>
                        <li>
                        <strong> Cookies and Tracking:</strong> Our site uses cookies and similar technologies to enhance user experience, for analytics, and for advertising. Details are in the Privacy Policy. By using the site, you agree to our use of cookies as described in the policy (with any consent mechanisms provided for certain regions). </li>
                        <li>
                        <strong> Children’s Privacy:</strong> Takshila’s Services are not directed to children under 13. We do not knowingly collect personal information from children under 13. If we learn that we have collected personal data from a child under 13 (or under the applicable age of consent in certain jurisdictions) without appropriate consent, we will promptly delete it. </li>
                        <li>
                        <strong> Questions:</strong> If you have any privacy-related questions or requests, please refer to the Privacy Policy for contact information or reach out to our support. We take user privacy seriously and will do our best to address your concerns. </li>
                        </ul>
                        <h3> 10. Disclaimers of Warranties </h3>
                        <ul>
                        <li>
                        <strong> As-Is Service:</strong> Takshila provides the website and Services on an “AS IS” and “AS AVAILABLE” basis . While we endeavor to keep our Services uninterrupted and secure, we make no guarantee that the Service will be continuous, timely, error-free, or free of viruses or other harmful components. Use of our platform (including downloading of any content or files) is at your own risk. </li>
                        <li>
                        <strong> Product Warranties: </strong> Takshila stands by the quality and authenticity of our jewelry. We guarantee that products will be as described in terms of precious metal purity (karat
                        of gold, etc.), gemstone specifications (carat weight, type of stone, etc.), and craftsmanship quality. If an item does not meet these express standards, your remedies are as outlined in the Returns/Defects section above. However, to the fullest extent permitted by law, we disclaim all other warranties, express or implied, including any implied warranties of merchantability, fitness for a particular purpose, title, and non-infringement. For example, we do not warrant that the jewelry will meet all of your subjective expectations or that the materials will never naturally wear or require upkeep. </li>
                        <li>
                        <strong> No Guarantee of Design Outcomes:</strong> Any use of our AI design feature or custom design services is at the user’s discretion. Takshila makes no warranty that the AIgenerated design suggestions will be suitable, unique, or that they will not unintentionally
                        resemble existing designs. We attempt to guide the AI to avoid known copyrighted styles , but we cannot absolutely guarantee that an AI-produced image is one-of-a-kind. By using the AI tool, you understand its outputs are generated by patterns in training data and could have
                        similarities with pre-existing artworks or designs. Takshila disclaims responsibility for any unintended similarities and provides the tool “as-is” for inspirational use. It remains the user’s responsibility to vet and refine the design to ensure it is acceptable. </li>
                        <li>
                        <strong> Third-Party Services &amp; Content:</strong> We make no warranties regarding any thirdparty services integrated with Takshila (such as payment gateways, Shopify hosting, or AI APIs). Any third-party content or links are provided for convenience, and Takshila is not responsible for their accuracy or reliability . </li>
                        <li>
                        <strong> No Other Promises:</strong> Except for what is explicitly stated by Takshila (for instance, any limited warranty that might accompany a product, or a specific guarantee in writing), no advice or information obtained from us or through the Services shall create any warranty not expressly stated in these Terms. Employees, artisans, or partners of Takshila are not authorized to make modifications to these warranties, so please do not rely on any oral or informal written assurances that are not reflected here or in official documentation. </li>
                        <li>
                        <strong> Consumer Law:</strong> In some jurisdictions, you may have rights that cannot be excluded by a Terms of Service. For instance, certain consumer protection laws may give you warranties or guarantees that products will be of acceptable quality and match their description.
                        Nothing in this section is intended to override rights you have under local law. Instead, this section applies to the maximum extent allowed by applicable law. If a disclaimer of implied warranty is not permitted in your jurisdiction, those implied warranties are limited to the shortest duration allowed, and our express warranties are limited as provided herein. </li>
                        <li>
                        <strong> Allergy or Sensitivity:</strong> Takshila uses standard industry materials (gold, silver, platinum, gemstones, etc.). We are not responsible for any allergic reactions or sensitivities you may have to these materials (such as nickel allergies from certain gold alloys). It is your responsibility to inquire about materials if you have known allergies. We can often provide hypoallergenic options on request (like 18k gold or platinum for nickel-free jewelry), but if no request is made, we deliver standard materials. No warranty is given that our products will be allergen-free for any particular individual. </li>
                        </ul>
                        <h3> 11. Limitation of Liability </h3>
                        <ul>
                        <li>
                        <strong> Indirect Damages:</strong> To the fullest extent permitted by law, Takshila and its affiliates, officers, employees, agents, partners, and suppliers shall not be liable for any indirect, incidental, special, consequential, or punitive damages . This includes, without limitation, damages for lost profits or revenues, loss of data, loss of goodwill, costs of cover (obtaining substitute goods or services), or other intangible losses arising out of or related to your use of (or inability to use) the Services, any product purchased through the Services, or any user content or third-party conduct on the Services. </li>
                        <li>
                        <strong> Direct Damages Cap:</strong> To the fullest extent permitted by law, the maximum aggregate liability of Takshila (and our affiliates and partners) to you for any claims arising from or related to these Terms or the use of the Services or products is limited to the greater of: (a) the total fees actually paid by you to Takshila for the product or service that gave rise to the claim, or (b) US $100. If the claim does not relate to a specific product or paid service, $100 is the cap. This means if you bought a ring for $500 and something went wrong, our liability for any and all claims related to that purchase would not exceed $500 (assuming that’s the amount you paid). If you haven’t made any purchase, our liability would be capped at $100. </li>
                        <li>
                        <strong> Release of Liability:</strong> You release Takshila from any and all liability for the results obtained or not obtained from the use of our Services. For example, if you use the AI design feature and invest time into a design that you later cannot produce or patent, you cannot hold Takshila liable for that lost time or opportunity. Similarly, if you meet another user via our community and engage in an off-platform transaction that goes poorly, Takshila bears no responsibility. </li>
                        <li>
                        <strong> Exceptions:</strong> The above limitations and exclusions apply regardless of the theory of liability – whether based in contract, warranty, tort (including negligence), strict liability or any other legal theory, even if Takshila has been advised of the possibility of such damages. However, nothing in these Terms is intended to exclude or limit liability that cannot be excluded under law. For instance, some jurisdictions do not allow the exclusion of liability for personal injury or death caused by a party’s negligence, or for gross negligence or willful misconduct. Likewise, some jurisdictions do not allow the exclusion of implied warranties or the exclusion or limitation of certain damages. In such jurisdictions, our liability will be limited to the maximum extent permitted by law. </li>
                        <li>
                        <strong> State Law Notice:</strong> For consumers residing in certain states (like New Jersey), the above limitation of liability may not apply to you in certain circumstances, to the extent that state law prohibits it. You may have specific rights that vary from state to state. We do not seek to limit your rights beyond what’s permitted by law. </li>
                        <li>
                        <strong> Timeliness of Claims:</strong> You agree that any claim or cause of action arising out of or related to use of the Services or these Terms must be filed within one (1) year after such claim or cause of action arose, or else it will be permanently barred. (This does not apply where prohibited by law – for example, some consumer protection claims might allow a longer period by statute.) </li>
                        </ul>
                        <h3> 12. Indemnification </h3>
                        <p> You agree to indemnify, defend, and hold harmless Takshila and its parent company, affiliates, officers, directors, agents, partners, employees, and suppliers from and against any and all third-party claims, liabilities, damages, losses, costs, or expenses (including reasonable attorneys’ fees) that arise out of or relate to </p>
                        <ul>
                        <li>
                        <strong> Your breach of these Terms:</strong> Any violation of these Terms or other policies by you, including any misuse of the Services contrary to our guidelines </li>
                        <li>
                        <strong> Your Content:</strong> Any User Content you submit or design (AI-generated or uploaded) that infringes, misappropriates, or otherwise violates any intellectual property, privacy, or other rights of any third party, or that violates any law. This means if someone else claims your design is theirs or that it caused harm, you will cover Takshila for any resulting costs or damages .</li>
                        <li>
                        <strong> Your Transactions:</strong> Any dispute or issue arising from your direct interactions or contracts with other users (e.g., if designers and customers somehow engage outside our platform or violate our rules and it causes a problem). </li>
                        <li>
                        <strong> Your unlawful conduct:</strong> This includes, but is not limited to, any fraud you commit, your intentional wrongdoing, or any violation of law (such as if you attempt to use Takshila to launder money, etc., which of course you shouldn’t). </li>
                        <li>
                        <strong> Your negligence or willful misconduct:</strong> For example, if you falsely claim a Takshila product harmed you when it was actually altered by you or misused, and we incur costs defending that false claim, you’d indemnify us. </li>
                        </ul>
                        <p> We reserve the right to handle our legal defense however we see fit, even when you are indemnifying us, in which case you agree to cooperate with us so we can execute a strategy (for instance, you may have to provide information or testimony in a lawsuit if needed). This indemnity obligation will survive termination of your relationship with Takshila and use of the Services. We will promptly notify you of any such claim and let you assume the defense, but we have the right to participate (at our cost) and approve any settlement to ensure it’s reasonable for us </p>

                        <h3> 13. Dispute Resolution and Governing Law </h3>
                        <ul>
                        <li>
                        <strong> Governing Law:</strong> These Terms and any disputes arising out of or relating to these Terms or the Services will be governed by and construed in accordance with the laws of the State of Florida, USA, and applicable federal United States law, without giving effect to any conflict of law principles that would cause the laws of another jurisdiction to apply. If you reside outside the U.S., you still agree that U.S. and Florida law governs your use of the Services and any dealings with Takshila, though you may have additional consumer rights under your local law. </li>
                        <li>
                        <strong> Initial Dispute Resolution:</strong> Most questions or concerns can be resolved informally by contacting Takshila customer support. You agree to try in good faith to settle any dispute or claim by contacting us first and providing a description of your issue before taking formal legal action. We will likewise attempt to resolve the dispute through our support channels before pursuing legal action against you. </li>
                        <li>
                        <strong> Arbitration Agreement:</strong> Please read this carefully – It affects your rights. You and Takshila agree that any dispute, claim, or controversy arising out of or relating to these Terms or the use of the Services or products sold by Takshila shall be resolved by binding arbitration on an individual basis, except for the exceptions set forth below. This includes disputes based on any legal theory, including contract, tort, statute, fraud, misrepresentation, or any other legal theory. </li>
                        <li>
                        <strong> Opt-Out:</strong> You may opt out of this arbitration provision within 30 days of first accepting these Terms by contacting us in writing (email is sufficient) and stating your intent to opt out. Your opt-out doesn’t affect any other parts of these Terms. </li>
                        <li>
                        <strong> Arbitration Procedure:</strong> The arbitration will be administered by a reputable arbitration provider under its Consumer Arbitration Rules. The arbitration will take place in English, and unless you and Takshila agree otherwise, it will happen in a mutually convenient location or via teleconference/videoconference if in-person is overly burdensome. Each party is responsible for their own costs, but the arbitrator can award fees and costs to the prevailing party where allowed by law. </li>
                        <li>
                        <strong> Authority of Arbitrator:</strong> The arbitrator can grant any relief that a court could, including monetary, declaratory, or injunctive relief on an individual basis. However, the arbitrator may not consolidate or join the claims of other persons or parties who may be similarly situated; every dispute must be arbitrated only on an individual basis. The arbitrator’s decision shall be final and binding and judgment on the award may be entered in any court of competent jurisdiction. </li>
                        <li>
                        <strong> Exceptions to Arbitration:</strong> Either party may choose to pursue a dispute in small claims court (if it qualifies) rather than arbitration. Also, either party may seek injunctive relief in a court of competent jurisdiction for intellectual property infringement or misuse (for example, Takshila could go to court for a temporary restraining order or injunction if someone misuses our trademarks or steals our trade secrets, and you could do the same if someone misused your IP in violation of these Terms). Such actions will not be deemed a waiver of the right to arbitrate other issues. </li>
                        <li>
                        <strong> Class Action Waiver:</strong> You and Takshila agree that any claims must be brought on an individual basis only, and not as a plaintiff or class member in any purported class or representative proceeding. The arbitrator has no authority to consider or resolve any claim or issue any relief on any basis other than an individual basis. No arbitration or proceeding will be combined with another without the prior written consent of all parties for all affected arbitrations or proceedings. </li>
                        <li>
                        <strong> Jurisdiction for Legal Proceedings:</strong> In the unlikely event that a dispute is found not subject to the arbitration clause (either because you opted out, or the clause is found unenforceable, or you fall under an exception), then you and Takshila agree to the jurisdiction of the state and federal courts located in Florida for any litigation. You waive any objections to venue in those courts, including objections based on inconvenience. </li>
                        <li>
                        <strong> Jury Trial Waiver:</strong> If for any reason a claim proceeds in court rather than arbitration, you and Takshila each waive any right to a jury trial. </li>
                        <li>
                        <strong> Limitation on Proceedings:</strong> As stated earlier, to the extent permitted by law, any dispute must be filed within one year of when it arose. This is to ensure timely resolution and that evidence is fresh. </li>
                        <li>
                        <strong> Confidentiality of Arbitration:</strong> Any arbitration proceedings, and any information disclosed during arbitration, shall be confidential and not used or disclosed outside the arbitration, except as needed to enforce the arbitration outcome or as required by law. </li>
                        </ul>
                        <p><strong> Review of Takshila Terms and Conditions – Recommended Additions and Clarifications </strong></p>
                        <p> The draft Terms and Conditions for Takshila is very comprehensive and well-structured. To further minimize liability and risk for Takshila and to cover any remaining legal, regulatory, moral, or societal considerations, here are several additional points and clarifications that could be incorporated: </p>
                        <h3> 14. Legal and Compliance Clauses </h3>
                        <ul>
                        <li>
                        <strong> Export &amp; Sanctions Compliance:</strong> Add a clause confirming that users are not in sanctioned countries or on restricted lists, and that they will comply with all U.S. export/import laws . For example, require users to represent that they are not located in or shipping to embargoed nations and will not use Takshila’s services in violation of export controls.  </li>
                        <li>
                        <strong> Anti-Money Laundering and Verification:</strong> Mention that Takshila may request identity verification for large transactions or suspicious orders to comply with anti-money laundering regulations. Users should agree to provide necessary information or documentation if required (e.g. for orders over a certain dollar amount or international shipments). </li>
                        <li>
                        <strong> Law Enforcement Cooperation:</strong> State explicitly that Takshila reserves the right to report any suspected fraud, illegal activity, or threats to the appropriate authorities . For instance, if an account is used for illicit purposes (attempted money laundering, use of stolen credit cards, trafficking of illegal goods, etc.), Takshila can terminate the account and work with law enforcement. </li>
                        <li>
                        <strong>Jurisdictional Use Limitations:</strong> Emphasize that users are responsible for compliance with all local laws and regulations when accessing the site. The draft does note global use and local law compliance – reinforcing that Takshila’s Services should not be used
                        where unlawful (including any local restrictions on jewelry materials, content, or online services). </li>
                        <li>
                        <strong> No Third-Party Beneficiaries:</strong> Include a statement that the Terms are for the benefit of the user and Takshila only, and no other person or entity has rights to enforce the Terms.
                        </li>                                                                    <li>
                        <strong> English Version Governs:</strong> If Takshila ever provides the Terms in multiple languages for global users, clarify that the English version is controlling in case of any conflict or ambiguity . For example: “Translations of these Terms may be provided for convenience. However, any inconsistency will be resolved in favor of the English version.” </li>
                        </ul>

                        <h3> 15. User Conduct and Account Use </h3>
                        <ul>
                        <li>
                        <strong> Prohibited Technical Misuse:</strong> Strengthen the acceptable use provisions by explicitly forbidding attempts to hack, disrupt, or misuse the platform. For example, state that users may not attempt to gain unauthorized access to any part of the site, introduce malicious code, attack our servers (e.g. via DDoS), or otherwise interfere with the proper working of the Services . </li>
                        <li>
                        <strong> Account Sharing and Protection: </strong> Add that users must not share their login credentials or allow others to use their account . The draft already notes users are responsible for all activity on their account; explicitly prohibiting sharing passwords or accounts reinforces security. You are responsible for maintaining the confidentiality of your password and may not share your account with anyone else. You agree to notify us of any unauthorized access. We are not liable for any loss from unauthorized use of your credentials. </li>
                        <li>
                        <strong> Harassment and Discrimination:</strong> Obscene, hateful, or unlawful content, abusive, harassing, or discriminatory behavior toward others on the platform is forbidden . This covers any user interactions (comments, messages, etc.) and gives Takshila authority to remove or ban users for such misconduct.  </li>
                        <li>
                        <strong> User Responsibility for Input Accuracy:</strong> Users are fully responsible for the accuracy of information they provide to Takshila. This includes order details (like ring size, engraving text, shipping address) and any design specifications. If a user provides incorrect specifications, Takshila will not be liable for resulting issues. For example, if a customer submits the wrong ring size or misspells an engraving, that’s not a “defect” on Takshila’s part. Takshila is not responsible for errors in your provided information. </li>
                        <li>
                        <strong> No Endorsement of User Interactions:</strong> Any arrangements or communications outside the platform are not endorsed or backed by Takshila. Previous sections already prohibits designers and customers from bypassing the platform (and notes Takshila isn’t liable for off-platform dealings). Additionally, Takshila is not responsible for any agreements or communications that occur outside of our Services. </li>
                        </ul>

                        <h3> 16. User Content and Community Guideline </h3>
                        <ul>
                        <li>
                        <strong> Views Expressed Disclaimer:</strong> User-generated content (designs, comments, reviews) reflects the views of the user alone, not Takshila’s opinions or endorsements. For instance: “Any opinions, advice, or designs posted by users are solely those of the original author and do not represent the views of Takshila </li>
                        <li>
                        <strong> No Liability for User Content: </strong> Takshila isn’t liable for content posted by users that it has not yet removed. Since Takshila will endeavor to moderate and remove violating content (per the Terms), given the real-time nature of the platform, some content might appear that violates rules, and Takshila cannot be held responsible for every user post in real time. Users should notify Takshila of any content they believe violates rights or policies, and Takshila will act as appropriate (as mentioned with the DMCA and content removal process). This disclaimer aligns with the Digital Millennium Copyright Act (DMCA) safe harbor principles and other online community standards. </li>
                        <li>
                        <strong> No Implied Endorsement or Verification: </strong> Takshila does not pre-approve or guarantee the accuracy of user-provided content (like design descriptions or materials claims on community-listed designs). Users buy community designs at their own risk, subject to Takshila’s production quality control, but any descriptive text or claims by the designer are not separately warranted by Takshila. Essentially, “Takshila does not guarantee that usercontributed descriptions or feedback are accurate or reliable.” This section discourages users from relying on unverified statements and prompts them to reach out to Takshila for any important clarifications before purchase. </li>
                        </ul>
                        <h3> 17. Product Safety, Quality, and Ethical Practices </h3>
                        <ul>
                        <li>
                        <strong> Substances used during Manufacturing Process Disclaimers: </strong> Takshila jewelry products may contain small amounts of chemicals such as lead (in crystal components) or nickel, as a normal particle of manufacturing processes. </li>
                        <li>
                        <strong> Not Intended for Children: </strong> Our jewelry is intended for adult use and is not designed or intended for children under the age of 13. Jewelry may contain small parts or materials not suitable for young children and may pose a choking hazard or cause allergic reactions. </li>
                        <li>
                        <strong> Conflict-Free and Ethical Sourcing: </strong> Takshila is committed to sourcing diamonds and gemstones from conflict-free suppliers and expects its partners to follow fair labor practices, including the prohibition of child or forced labor. We support initiatives such as the Kimberley Process to prevent trade in conflict diamonds. </li>
                        <li>
                        <strong> Quality and Care Disclaimers: </strong> Normal wear-and-tear, tarnishing, or damage from misuse, accidents, or improper care is not considered a manufacturing defect and will not be eligible for return, refund, or free repair. Jewelry may naturally tarnish or show wear over time, especially metals like silver or gold plating. Proper care is the customer’s responsibility, such as avoiding harsh chemicals and having settings checked periodically. Failure to follow care instructions voids any implied warranty. </li>
                        <li>
                        <strong> Customer’s Post-Delivery Responsibility:</strong> Once an item has been delivered and accepted, ownership and responsibility pass entirely to the customer. We strongly recommend insuring valuable pieces for loss, damage, or theft, as Takshila cannot be responsible for events that occur after delivery. </li>
                        <li>
                        <strong> Future Services or Features: </strong> If Takshila introduces any warranty programs, maintenance services, or cleaning plans in the future, those will be governed by separate terms. Except as expressly stated, Takshila makes no guarantee that your jewelry will last for a specific period of time; proper care will affect longevity. </li>
                        </ul>
                        <h3> 18. Additional Disclaimers and Liability Protections </h3>
                        <ul>
                        <li>
                        <strong> No Professional Advice: </strong> All information on our site, including design tips or gemstone education content, is provided for general informational purposes only and does not constitute professional advice (legal, financial, or otherwise). You should consult appropriate professionals for advice tailored to your needs. Takshila is not liable for actions taken based on information provided through the Services.</li>
                        <li>
                        <strong>  User’s Use at Own Risk:</strong> By using our Services, you agree that you do so at your sole risk. You are responsible for any content you submit and for any consequences of using the designs or products obtained through Takshila. </li>
                        <li>
                        <strong> Limitation of Remedies:</strong> The sole remedies available to you are those expressly provided in these Terms, such as repair, replacement, or refund for defective products. You may not seek other damages or equitable relief outside the remedies set forth herein. </li>
                        <li>
                        <strong> No Indirect or Punitive Damages – Global Enforcement: </strong> To the fullest extent permitted by law, Takshila excludes liability for incidental, consequential, special, or punitive damages. Some jurisdictions do not allow certain liability exclusions; in such cases, Takshila’s liability will be limited to the maximum extent permitted by applicable law. </li>
                        <li>
                        <strong> No Warranty of Unique Outcomes:</strong> Creative outcomes from AI-generated designs or other design tools can vary, and uniqueness is not guaranteed. Takshila does not warrant that any design will be one-of-a-kind or free from unintentional similarities to existing designs. It is the user’s responsibility to ensure no intellectual property infringement. </li>
                        <li>
                        <strong> Third-Party Beneficiaries of Disclaimers:</strong> The disclaimers and limitations of liability set forth in these Terms also apply to Takshila’s affiliates, suppliers, and service providers (including AI technology providers and manufacturing partners) to the fullest extent permitted by law </li>
                        </ul>
                        <h3> 19. Communications and Miscellaneous </h3>
                        <ul>
                        <li>
                        <strong> Electronic Communications Consent: </strong> By using our Services, you consent to receive communications from Takshila electronically. You agree that we can contact you via the email address (and/or phone number, if provided for text updates) you supply, and that electronic delivery of notices, disclosures, and agreements has the same legal effect as physical delivery. You agree to receive certain emails—such as order confirmations, shipping updates, and other service-related communications—which are necessary for your transactions and cannot be opted out of. Marketing communications will only be sent in accordance with your preferences and applicable law (e.g., CAN-SPAM, GDPR). </li>
                        <li>
                        <strong> Opt-Out of Marketing:</strong> You may opt out of promotional or marketing emails at any time by using the unsubscribe link in such emails or contacting us as described in our Privacy Policy. This will not affect your ability to receive necessary service-related communications. </li>
                        <li>
                        <strong> Updates to Terms and Policies:</strong> Takshila may update or modify these Terms at any time. Material changes will be communicated to you via email or prominent notice on our site in addition to posting the updated Terms. Continued use of the Services after changes become effective constitutes your acceptance of the revised Terms. </li>
                        <li>
                        <strong> Changes to Services:</strong> We may modify, suspend, or discontinue any part of the Services (including any feature, product, or content) at any time without notice or liability. We also reserve the right to impose limits on use or storage at our sole discretion.</li>
                        <li>
                        <strong> No Waiver: </strong> If we do not enforce a provision of these Terms, we are not waiving our right to enforce it later. Any waiver must be in writing and signed by an authorized Takshila representative. </li>
                        <li>
                        <strong> Severability:</strong> If any provision of these Terms is held invalid, illegal, or unenforceable, that provision will be enforced to the maximum extent permissible, and the remaining provisions will remain in full force and effect. </li>
                        <li>
                        <strong> Entire Agreement and No Reliance: </strong> These Terms (along with any incorporated policies, such as our Privacy Policy, Cookie Policy, and any specific program or service terms) constitute the entire agreement between you and Takshila regarding your use of the Services and supersede all prior agreements or understandings, whether oral or written. You acknowledge that you have not relied on any representation, warranty, or statement not expressly set out in these Terms. No oral or informal statement will create any obligation not contained herein. </li>
                        <li>
                        <strong> Future Policy Integration:</strong> Participation in any additional Takshila programs (e.g., Rewards, Referral) will also be subject to their specific terms, which will govern in the event of a conflict with these Terms. </li>
                        <li>
                        <strong> Assignment: </strong> You may not assign or transfer any rights or obligations under these Terms without our prior written consent. We may assign or transfer our rights and obligations without restriction, including in connection with a merger, acquisition, or sale of assets. These Terms will bind and benefit each party’s successors and permitted assigns. </li>
                        <li>
                        <strong> Relationship of Parties:</strong> Nothing in these Terms creates an agency, partnership, or joint venture between you and Takshila. You do not have authority to bind Takshila in any way. </li>
                        <li>
                        <strong> Notices: </strong> We may provide notices by email, postal mail, postings within the Services, or other legally acceptable means. You are responsible for keeping your contact information current. Official legal notices to Takshila should be sent to our designated business or registered agent address (as provided in the Contact Information section). </li>
                        <li>
                        <strong> Governing Law Nuance: </strong> These Terms are governed by the laws of the State of Florida and applicable U.S. federal law. The United Nations Convention on Contracts for the International Sale of Goods (CISG) does not apply. </li>
                        <li>
                        <strong> Arbitration Opt-Out Reminder: </strong> If you do not wish to be bound by the arbitration clause in these Terms, you must contact us at (aikanshtyagi@takshila.co) within 30 days of first agreeing to these Terms. </li>
                        <li>
                        <strong> Force Majeure:</strong> Takshila is not liable for any delay or failure to perform caused by events beyond our reasonable control, including natural disasters, acts of government, war, terrorism, riots, labor disputes, supply shortages, or internet/service provider failures. </li>
                        <li>
                        <strong> Headings: </strong> Section titles and headings are for convenience only and have no legal effect. </li>
                        <li>
                        <strong>Survival: </strong> Any provisions of these Terms that by their nature should survive termination (including indemnification, limitation of liability, dispute resolution, and intellectual property terms) will survive termination of your use of the Services. </li>
                        </ul>
                        <h3> 20. Contact Information </h3>
                        <p> If you have any questions, concerns, or feedback about these Terms &amp; Conditions, or if you need to contact us for any reason, you can reach Takshila at: </p>
                        <ul>
                        <li>
                        <strong> Email:</strong><a href="mailto:aikanshtyagi@takshila.co"> aikanshtyagi@takshila.co</a> </li>
                        <li>
                        <strong> Customer Service Contact:</strong> Via our website’s Contact Us section for the most update Contact Information. </li>
                        <li>
                        <strong> Business Address: </strong> 5229 4th St, Zephyrhills, FL (USA) 33542 </li>
                        </ul>
                        <p> We value honesty, transparency, and customer trust. Takshila’s mission is not only to empower creativity in jewelry design but also to conduct business in a way that is fair and safeguards both our customers and our company. We appreciate you taking the time to read these Terms. Happy designing and shopping on Takshila! </p>

                            </div>
                
                        </section>        
                            </>
    );
}
